// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHZ3ooknCKDueo9E-m4Ok8XFAl0pm0uQ',
    appId: '1:983098263159:web:e2ad12830481682ba2a872',
    messagingSenderId: '983098263159',
    projectId: 'flutter-application-1-f2388',
    authDomain: 'flutter-application-1-f2388.firebaseapp.com',
    storageBucket: 'flutter-application-1-f2388.appspot.com',
    measurementId: 'G-ZKYRZL5V57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAahOeqdY_t2StTKqf3_8wGfYvr1yQe7TQ',
    appId: '1:983098263159:android:bdad30522928352aa2a872',
    messagingSenderId: '983098263159',
    projectId: 'flutter-application-1-f2388',
    storageBucket: 'flutter-application-1-f2388.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNWZ7AR-7f25zivBEEcF67KjxG86RG2kc',
    appId: '1:983098263159:ios:7a76dc8ff2f96e8ea2a872',
    messagingSenderId: '983098263159',
    projectId: 'flutter-application-1-f2388',
    storageBucket: 'flutter-application-1-f2388.appspot.com',
    iosClientId: '983098263159-p3h1221p13lfe5l5oopfv57shp3tb57j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNWZ7AR-7f25zivBEEcF67KjxG86RG2kc',
    appId: '1:983098263159:ios:7a76dc8ff2f96e8ea2a872',
    messagingSenderId: '983098263159',
    projectId: 'flutter-application-1-f2388',
    storageBucket: 'flutter-application-1-f2388.appspot.com',
    iosClientId: '983098263159-p3h1221p13lfe5l5oopfv57shp3tb57j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication4',
  );
}
